### PR TITLE
Update SE_Topics.md

### PR DESCRIPTION
**Pull request by fabiopetrillo**
Adding 3 suggestions.

### CODE REVIEW

**Comment by MichaelHilton** [comment]
I changed Configuration to Configuration Management.  If you think that is in correct, feel free to clarify.

**Comment by fabiopetrillo** [comment]
Perfect.

**Comment by snadi** [comment]
Was this merged? I still see the old version of the list in this repo :S

**Comment by fabiopetrillo** [comment]
Same... :-(

**Pull request closed without merging**
